version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-254-218.compute-1.amazonaws.com
            database: dvjikqc1fvj4u
            user: mjwmixgvwpuvax
            password: 15a17903a6c0d3c61bf4b6a01e3b38bcfebd13c1ef63af77f55681478c8f4a9c
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
